### ISSUE TITLE
[Bug] mnemosyne-hermes 0.7.2 incompatible with latest stable core 3.15.1: ImportError write_policy_operation on every tool call

### ISSUE THREAD

**Issue by LukaAsceric** [mnemosyne-oss/mnemosyne#1019]
## Bug Description

mnemosyne-hermes 0.7.2 fails on every tool call when paired with the latest **stable** core library mnemosyne-memory 3.15.1: the tool call path imports a symbol that does not exist in the released core.

```
Mnemosyne tool 'mnemosyne_stats' failed: cannot import name 'write_policy_operation' from 'mnemosyne.core.filters' (site-packages/mnemosyne/core/filters.py)
```

The write-policy import was introduced in 0.7.2 ("fix(config): enforce write policy at admission boundary (#955)") and appears at:
- mnemosyne_hermes/__init__.py:2298 and :2528: `from mnemosyne.core.filters import write_policy_operation`

mnemosyne-memory 3.15.1 (latest stable) has no `write_policy_operation` in mnemosyne.core.filters. Version 0.7.1 does not contain the write-policy code at all and works fine with 3.15.1. The 0.7.2 pairing seems to target the unreleased 4.0.0 beta core, but neither the wheel metadata nor the release notes state a core-library floor, so upgrading the plugin alone (the obvious "update the plugin" action) bricks every tool call.

## Steps to Reproduce

1. `pip install -U mnemosyne-memory[embeddings] mnemosyne-hermes` (resolves to core 3.15.1 + plugin 0.7.2)
2. Invoke any tool via the provider, e.g. mnemosyne_stats
3. Observe ImportError above

## Expected Behavior

Either (a) mnemosyne-hermes 0.7.2 declares its core requirement so pip pairs it with a compatible core (or the 4.0.0b line), or (b) a stable core release carrying `write_policy_operation` exists before 0.7.2 lands as the default pip resolution.

## Workaround

Pin `mnemosyne-hermes==0.7.1` (verified working with core 3.15.1: mnemosyne_stats and mnemosyne_recall return correct results).

## Secondary robustness note (same subsystem)

A config value of `tools: None` (the *string* "None", e.g. written by a config tool, in Hermes config.yaml under memory.mnemosyne) is not caught at provider init. It passes through the string-splitting path in `_configured_tool_schemas()` (hermes_memory_provider/__init__.py ~1710), becomes the tool name "None", and the validation error then fires on **every** tool call with the confusing message `Unknown Mnemosyne tool(s) in memory.mnemosyne.tools: None`. Suggestion: treat the strings "None"/"null"/"" as unconfigured (fall back to all tools), and/or run this validation at provider initialization so operators see it at startup instead of losing the whole tool surface at call time.

Cross-reference (found while triaging a misfiled issue): NousResearch/hermes-agent#118260

**Comment by dplush** [comment]
Confirmed duplicate of #1014.

Independent wheel check: `mnemosyne-hermes==0.7.2` declares `mnemosyne-memory[embeddings]>=3.11.1`; with `mnemosyne-memory==3.15.1`, the installed core has no `write_policy_operation`, while the wrapper imports it on the tool-call path. The resolver-valid pair is therefore runtime-incompatible. The reported `0.7.1` workaround is consistent with the released-pair evidence already recorded on #1014.

The release-contract repair is tracked by #1016, which raises the wrapper floor to a compatible released core and has passing checks. The secondary `tools: "None"` configuration note is separate scope and should be tracked independently if still reproducible.
